-- CREATE TABLE members(
--     id BIGSERIAL PRIMARY KEY,
--     role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
--     name VARCHAR(500) NOT NULL,
--     phone VARCHAR(500) NOT NULL UNIQUE,
--     email VARCHAR(500) NOT NULL UNIQUE,
--     password VARCHAR(500) NOT NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
-- )


-- ALTER TABLE members
-- ADD COLUMN location VARCHAR(500)